---
- name: "Playing with Ansible and Git"
  hosts: localhost
  connection: local 
  gather_facts: no

  tasks:
  - name: create data.json
    copy:
      contents: |
        {
          "UserName": "admin", 
    	    "Password": "redhat123" 
        }
      dest: data.json

  - name: Copy script content to 
    copy:
      content: |
        #!/bin/bash
        #
        JSON_FILE=${0}.json
        xauthtoken=$(curl -i -H "Content-Type: application/json" -H "OData-Version: 4.0" -X POST --data "@data.json" https://192.168.155.9/redfish/v1/SessionService/Sessions/ --insecure  | grep X\-Auth\-Token | awk '{print $2}')
        echo $xauthtoken

        curl -v --insecure --silent \
        -X GET \
        -H 'X-Auth-Token: '$xauthtoken \
        -L \
        https://192.168.155.9/redfish/v1/Systems/1
      dest: "power_check.sh"
  
  - name: Run the script 
    ansible.builtin.script: ./power_check.sh
    register: file_content
   
  - name: "Print the file content to a console"
    debug:
      msg: "{{ file_content.stdout }}"
    
