---
- name: "Playing with Ansible and Git"
  hosts: localhost
  connection: local 

  tasks:
  - name: Check iLO status
    uri:
      url: https://192.168.155.9/redfish/v1/SessionService/Sessions/
      method: GET
      body_format: json
      force_basic_auth: yes
      user: admin
      password: redhat123
      validate_certs: no
      headers:
        Content-Type: "application/json"
    register: "output"
    
  - debug: var=output.stdout_lines
