---
- name: "Playing with Ansible and Git"
  hosts: localhost
  connection: local 

  tasks:
  - name: Create user and password file
    file:
      path: "data.json"
      state: touch
  
  - name: copy username and password to  data.json
    copy:
      content: |
        { 
              "UserName": "admin", 
              "Password": "redhat123"
        }
    dest: data.json

  - name: Create a new file with permissions
    file:
      path: "power_check.sh"
      state: touch
      mode: 0755
      
  - name: Copy script content to 
    copy:
      content: |
        #!/bin/bash
        #
        JSON_FILE=${0}.json
        xauthtoken=$(curl -i -H "Content-Type: application/json" -H "OData-Version: 4.0" -X POST --data "@data.json" https://bmc1/redfish/v1/SessionService/Sessions/ --insecure  | grep X\-Auth\-Token | awk '{print $2}')
        echo $xauthtoken

        curl -v --insecure --silent \
        -X GET \
        -H 'X-Auth-Token: '$xauthtoken \
        -L \
        https://192.168.155.9/redfish/v1/Systems/1 \
        > $JSON_FILE        
      dest: "power_check.sh"
  
  - name: Run the script 
    ansible.builtin.script: 
      cmd ./power_check.sh
  
  - name: "Read a file content"
    shell: |
      cat power_check.json
    register: file_content

  - name: "Print the file content to a console"
    debug:
      msg: "{{ file_content.stdout }}"
    
