---
- name: "Mount iso for iLO"
  hosts: localhost
  connection: local 
  gather_facts: no

  tasks:
  - name: Mount iso 
    ansible.builtin.expect:
      command: ssh {{ ansible_user }}@{{ ilo_ip }} vm cdrom insert http://192.168.155.98:8082/v1/AUTH_S3/S3/foreman-discovery-image-3.8.0-1.iso
      responses:
        (?i)Are you sure you want to continue connecting (yes/no/[fingerprint])?: "yes"
        (?i)admin@192.168.155.9\'s password: '{{ ansible_password }}'
    no_log: true
