---
- name: "One time boot setup"
  hosts: localhost
  connection: local 
  gather_facts: no

  tasks:
  - name: create data.json
    copy:
      content: |
        {  
          "UserName": '{{ ansible_user }}', 
          "Password": '{{ ansible_password }}' 
        }
      dest: data.json
      
  - name: Copy script content to 
    copy:
      content: |
        #!/bin/bash
        #

        xauthtoken=$(curl -i -H "Content-Type: application/json" -H "OData-Version: 4.0" -X POST --data "@data.json" https://{{ ilo_ip }}/redfish/v1/SessionService/Sessions/ --insecure  | grep X\-Auth\-Token | awk '{print $2}')
        echo $xauthtoken

        curl -v --insecure --silent \
        -X PATCH -L \
        -H 'Content-Type: application/json' \
        -H 'X-Auth-Token: '$xauthtoken \
        --data '
        {
          "Boot": {
                   "BootSourceOverrideTarget": "Cd", 
                   "BootSourceOverrideEnabled": "Once", 
                   "UefiTargetBootSourceOverride": null
                  }
        }' \
        https://{{ ilo_ip }}/redfish/v1/Systems/1 \
        > onetimeboot.json
      dest: "onetimeboot.sh"    
      
  - name: Display the JSON file content
    shell: cat onetimeboot.json
    register: result
  
  - name: save the Json data to a Variable as a Fact
    set_fact:
      jsondata: "{{ result.stdout | from_json }}"
