---
- name: "Power On"
  hosts: localhost
  connection: local 
  gather_facts: no

  tasks:
  - name: create data.json
    copy:
      content: |
        {  
          "UserName": '{{ ansible_user }}', 
          "Password": '{{ ansible_password }}' 
        }
      dest: data.json

  - name: Copy script content to 
    copy:
      content: |
        #!/bin/bash
        #
        xauthtoken=$(curl -i -H "Content-Type: application/json" -H "OData-Version: 4.0" -X POST --data "@data.json" https://{{ ilo_ip }}/redfish/v1/SessionService/Sessions/ --insecure  | grep X\-Auth\-Token | awk '{print $2}')
        echo $xauthtoken

        curl -v --insecure --silent \
        -X POST -L \
        -H 'X-Auth-Token: '$xauthtoken \
        -H 'Content-Type: application/json' \
        --data '{ "ResetType": "On" }' \
        https://{{ ilo_ip }}/redfish/v1/Systems/1/Actions/ComputerSystem.Reset \
        > $power_on.json

      dest: "power_on.sh"
  
  - name: Run the script 
    ansible.builtin.script: ./power_on.sh
   
  - name: Display the JSON file content
    shell: cat power_on.json
    register: result

  - name: save the Json data to a Variable as a Fact
    set_fact:
      jsondata: "{{ result.stdout | from_json }}"

  - name: Print the msg
    debug:
      msg: "{{ jsondata.PowerState }}"
