
---
- name: "Provision"
  hosts: localhost
  connection: local 
  gather_facts: no

  tasks:
  - name: create sat_host.json
    copy:
      content: |
        {
           "discovered_host": {
           "hostgroup_id": "{{ HG_ID }}",
           "location_id":"2",
           "organization_id":"1",
           "build":"true"
           }
        }
      dest: sat_host.json

  - name: Copy script content to 
    copy:
      content: |
         curl -v --insecure --silent \
         -X GET -L \
         -u {{ lookup("env", "SATELLITE_USERNAME") }}:{{ lookup("env", "SATELLITE_PASSWORD") }} \
         -H 'Content-Type: application/json' \
         --data '{}' \
         https://satellite.tingnkai.com/api/v2/discovered_hosts \
         > provision.json

         #get the host id
         id=$(cat provision.json | grep -oP '"\id\":.{0,3}' | cut -d ':' -f 2)
         echo $id

         curl -v --insecure --silent \
         -X PUT -L \
         -u {{ lookup("env", "SATELLITE_USERNAME") }}:{{ lookup("env", "SATELLITE_PASSWORD") }} \
         -H 'Content-Type: application/json' \
         --data @sat_host.json \
         https://satellite.tingnkai.com/api/v2/discovered_hosts/$id \
         >> provision.json
      dest: "provision.sh"
  
  - name: Run the script 
    ansible.builtin.script: ./provision.sh
   
  - name: Display the JSON file content
    shell: cat provision.json
    register: result
