
---
- name: "Delete satellite Host"
  hosts: localhost
  connection: local 
  gather_facts: no

  tasks:
  - name: Copy script content to 
    copy:
      content: |
         curl -v --insecure --silent \
         -X GET -L \
         -u {{ ansible_user }}:{{ ansible_password }} \
         -H 'Content-Type: application/json' \
         --data '{}' \
         https://satellite.tingnkai.com/api/v2/hosts \
         > sat_host.json
         
         #get the host id
         id=$(cat sat_host.json | grep -oP '\"{{ ilo_ip }}\".{0,1500}' | grep -oP '"\id\":.{0,3}' | cut -d ':' -f 2)
         echo $id
         
         curl  -X DELETE  -L -v --insecure --silent -u {{ ansible_user }}:{{ ansible_password }} https://satellite.tingnkai.com/api/v2/hosts/$id >> sat_host.json 
         
      dest: "del_sat_host.sh"
  
  - name: Run the script 
    ansible.builtin.script: ./del_sat_host.sh
    
  - name: Display the JSON file content
    shell: sat_host.json
    register: result
