
---
- name: "Delete satellite Host"
  hosts: localhost
  connection: local 
  gather_facts: no

  tasks:
  - name: Copy script content to 
    copy:
      content: |
         curl -v --insecure --silent \
         -X GET -L \
         -u {{ ansible_user }}':{{ ansible_password }}' \
         -H 'Content-Type: application/json' \
         --data '{}' \
         https://satellite.tingnkai.com/api/v2/hosts \
         > sat_host.json
      dest: "get_sat_host.sh"
  
  - name: Run the script 
    ansible.builtin.script: ./get_sat_host.sh
