
---
- name: "Delete satellite Host"
  hosts: localhost
  connection: local 
  gather_facts: no

  tasks:
  - name: Copy script content to 
    copy:
      content: |
         curl -v --insecure --silent \
         -X GET -L \
         -u {{ ansible_user }}:{{ ansible_password }} \
         -H 'Content-Type: application/json' \
         --data '{}' \
         https://satellite.tingnkai.com/api/v2/hosts \
         > sat_host.json
         
         > get host id
         #get the host id
         id=$(cat sat_host.json | grep -oP '\"192.168.155.9\".{0,2000}' | grep -oP '"content_facet_attributes".{0,10}' | grep -oP '"\id\":.{0,3}' | cut -d ':' -f 2)
         echo $id
         
         curl -X GET -s -k -u {{ ansible_user }}:{{ ansible_password }} https://satellite.tingnkai.com/api/v2/hosts/$id | json_reformat
         
      dest: "get_sat_host.sh"
  
  - name: Run the script 
    ansible.builtin.script: ./get_sat_host.sh
